name: Test OpenWrt Build.yml Structure

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dummy dependencies
        run: |
          echo "Dummy apt install to test syntax"
          sudo apt update
          sudo apt install -y cowsay

      - name: Simulate OpenWrt clone
        run: |
          echo "Simulating OpenWrt clone"
          mkdir openwrt
          cd openwrt
          echo "Simulating feeds update/install"
          echo "Done"

      - name: Simulate patch apply
        run: |
          echo "Simulating patch copy"

      - name: Simulate config copy
        run: |
          echo "Simulating .config copy"

      - name: Simulate build
        run: |
          cd openwrt
          echo "Running make defconfig (simulated)"
          echo "Running make -j1 V=sc (simulated)"

      - name: Simulate firmware upload
        run: |
          echo "Simulating artifact upload"
