name: OpenWrt Debug Build

on:
  workflow_dispatch:

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Show uploaded .config
        run: |
          cat .config

      - name: Check selected target
        run: |
          grep CONFIG_TARGET .config

      - name: List selected device
        run: |
          grep CONFIG_TARGET_ath79_generic_DEVICE_ .config
