name: Build Environment Check

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  check-env:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Update and install dependencies
      run: |
        sudo apt update
        sudo apt install -y build-essential gcc g++ make python3 patch zlib1g-dev libncurses5-dev git wget unzip
